"""Central CSV schemas. Keeping headers here prevents format drift."""

SCHEMAS = {
    "profile": ["name", "created_at"],
    "subjects": [
        "id",
        "name",
        "color",
        "description",
        "target_score",
        "created_at",
        "catalog_key",
        "name_vi",
    ],
    "tasks": [
        "id",
        "title",
        "description",
        "subject_id",
        "deadline",
        "priority",
        "estimated_minutes",
        "status",
        "created_at",
        "completed_at",
    ],
    "study_sessions": [
        "id",
        "subject_id",
        "task_id",
        "date",
        "start_time",
        "planned_minutes",
        "actual_minutes",
        "note",
        "status",
        "created_at",
    ],
    "notes": ["id", "title", "subject_id", "content", "created_at", "updated_at"],
    "flashcards": [
        "id",
        "subject_id",
        "question",
        "answer",
        "difficulty",
        "correct_count",
        "wrong_count",
        "last_reviewed",
        "created_at",
    ],
    "quizzes": ["id", "subject_id", "title", "description", "created_at"],
    "quiz_questions": [
        "id",
        "quiz_id",
        "question_text",
        "option_a",
        "option_b",
        "option_c",
        "option_d",
        "correct_option",
        "explanation",
    ],
    "quiz_results": [
        "id",
        "quiz_id",
        "score",
        "total",
        "accuracy",
        "duration_seconds",
        "completed_at",
    ],
    "settings": ["key", "value"],
}
